# Generated by Django 5.1.6 on 2025-03-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legoset',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='legoset',
            name='lego_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
