# Generated by Django 5.1.6 on 2025-03-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_remove_legoset_quantity_alter_legoset_lego_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='legoset',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
